version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - ./install.sh
  build:
    commands:
      - ./build.sh
  artifacts:
    files:
      - **
    name: cloudAssemblyFiles
    base-directory: cdk/cdk.out
cache:
  paths:
  - cdk/node_modules
  - lambdas/jobSubmitter/node_modules
